import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={``}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
       <main className="pt-[80px] flex-grow">
    {children}
  </main>
        <Footer />
        </body>
    </html>
  );
}
